services:
  apilm:
    build: .
    container_name: apilm
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - MODEL_NAME=${MODEL_NAME}
      - MODEL_PATH=${MODEL_PATH}
    volumes:
      - ./app:/app
      - ./data:/data
      - ./models:${MODEL_PATH}
    restart: unless-stopped